### ISSUE TITLE
Where are my coinZ???

### ISSUE THREAD

**Issue by Roshaff** [anthony19114/MyBitcoinZ#11]
Hello,

I sent my bitcoinz from Trade.cryptobroker on 13th december and they don't appear in "MybitcoinZ wallet" What should I do? Thanks in advance!

**Comment by jfont555** [comment]
I have the same problem... Have you found any solution?

**Comment by Roshaff** [comment]
Hi, yes. I recieved them on the 4th or 5th day. No customer service though. Nobody replied. I wrote a message to the BitcoinZ official FB and they replied, but then I recieved the coins so I can’t say if they could be useful, because I no longer needed their help. Don’t worry too much. It takes quite long time obviously. Good luck.

**Comment by anthony19114** [comment]
MyBitcoinZ is no longer supported by this repository, and has no technical support.

**Comment by Roshaff** [comment]
Well, good to know that. But what happens now when I try to send my Btcz to another place and I get Error 502? There must be somebody, anybody who takes care of that? Now what's next?

**Comment by Roshaff** [comment]
Ok, where should we address if there are any future issues or should we use another wallet? Thank you!

**Comment by jfont555** [comment]
@Roshaff Thank you for your response! I solved my problem too (just need to index & search for founds).  @anthony19114is MyNitcoinZ discontinued? We should change our btcz wallet? Thanks in advance!
