### ISSUE TITLE
Tx confirmed on the BitcoinZ blockchain, but not reflected in the wallet

### ISSUE THREAD

**Issue by ghost** [anthony19114/MyBitcoinZ#12]
Here is my receive address, generated by the MyBitcoinZ wallet:

![screen shot 2017-12-31 at 9 15 16 pm](https://user-images.githubusercontent.com/13460199/34465168-08e0cb94-ee70-11e7-8504-f3021e617718.png)

Here's that address in BitcoinZ Explorer, with two confirmed incoming transactions: https://explorer.bitcoinz.site/address/t1TfkD4ynbX51NyCbYbM3nFvtrThajo8LHv

And here's the home screen of the MyBitcoinZ wallet: 

![screen shot 2017-12-31 at 9 22 27 pm](https://user-images.githubusercontent.com/13460199/34465193-c52ab81e-ee70-11e7-8d12-6c347e44e7cc.png)

And the transaction history inside "Personal Wallet"... not reflecting the above transactions:

![screen shot 2017-12-31 at 9 17 09 pm](https://user-images.githubusercontent.com/13460199/34465169-0c5b6856-ee70-11e7-96c1-b9fd974b6015.png)

**Comment by anthony19114** [comment]
MyBitcoinZ is no longer supported by this repository, and has no technical support.
