### ISSUE TITLE
How to backup the .dat file on Windows 10?

### ISSUE THREAD

**Issue by marciotrader** [anthony19114/MyBitcoinZ#5]
Hi there.

I'm not be able to find the .dat file on Windows 10...
Any suggestion on how to do that?

I have another local wallet of another cryptocoin also on Windows, and under "Roaming" Windows folder are all files related to that wallet; but I can't find any similar folder structure on my MyBitcoinZ local wallet...

Appreciate any support from you...

**Comment by TOXid** [comment]
@marciotrader This is not local wallet, just webGUI gor bitpay/copay fork.
If u need local - u need to run full node wallet https://github.com/bitcoinz-pod/bitcoinz-wallet/releases
