### ISSUE TITLE
Wallet Sync -504

### ISSUE THREAD

**Issue by gixer271** [anthony19114/MyBitcoinZ#6]
The wallet wont sync giving error - 504 

Windows version

Any idea? When i installed it didn't install into my programs, just runs from the download folder. Should i delete folder , re install & try to recover my wallet with the pass phrase?

Thanks for any help

**Comment by oadsifuh** [comment]
Wait for a response before deleting... I have the same issue. I tried to restore my wallet on another PC and I could not restore my wallet with the 12 word passphrase, I get the message that it is not registered!?

EDIT:
My wallet is now synced, looks like some sort of blockchain communication error/delay

**Comment by anthony19114** [comment]
Ill close this issue for now, just respond and Ill re-open it.
