### ISSUE TITLE
Can't Send Funds

### ISSUE THREAD

**Issue by tjated** [anthony19114/MyBitcoinZ#9]
Trying to send results in message via Windows version reporting can't connect:
<img width="192" alt="screen shot 2017-11-20 at 10 53 05 am" src="https://user-images.githubusercontent.com/29543054/33030509-1392af26-cde1-11e7-9215-2d89bbf3ad55.png">

**Comment by anthony19114** [comment]
**MyBitcoinZ is no longer supported by this repository, and has no technical support.
**
